"""please work

Revision ID: 79352e5efea3
Revises: b5ad4a53e2fa
Create Date: 2023-12-13 00:28:40.019917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79352e5efea3'
down_revision = 'b5ad4a53e2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
